### ISSUE TITLE
Fails reporting invalid character in readme.md

### ISSUE THREAD

**Issue by decafbad** [UdashFramework/udash.g8#14]
```
$ sbt new UdashFramework/udash.g8
# after asking sbt version:
Exiting due to error in the template: /tmp/giter8-9785688750883
File: /tmp/giter8-(*)/src/main/g8/packager/README.md, 12:19: invalid character
```
/tmp gets cleaned afterwards. I couldn't find how to keep temp files.

Debian 10, Oracle JDK 8

**Comment by ddworak** [comment]
Hi! Thanks for reporting this. It seems to have slipped away as a warning for me locally and on Travis (https://travis-ci.org/UdashFramework/udash.g8):
```
Falling back to file copy for /home/travis/build/UdashFramework/udash.g8/src/main/g8/packager/README.md: File: /home/travis/build/UdashFramework/udash.g8/src/main/g8/packager/README.md, 12:19: invalid character '`'
```

Fixed now with https://github.com/UdashFramework/udash.g8/commit/1903212d1f358f90e70ae8b3a7c1f3c4a4a3f169. I'll take detailed look at how we can detect this issue after the weekend.

**Comment by ddworak** [comment]
`g8Test` only logs issues to `stdout` without any warning or error, whereas `sbt new` can fail on some of those. I've made an attempt to setup an integration test for this, but for some reasons I cannot force Travis to pipe any standard input to the task to even accept the default template values. We'll have to be more careful and wait for scripted test fix to ensure this never happens again.
