### ISSUE TITLE
Feature request: web worker

### ISSUE THREAD

**Issue by catap** [UdashFramework/udash.g8#24]
I feel that using web-worker is quite often.

Maybe it isn't so bad idea to add to default g8 template sub project with worker?

**Comment by ddworak** [comment]
Hi @catap! 

Is it though? I could agree that the browser support is nearly universal right now, but I don't see many apps using them - certainly not your typical web apps. There's a niche in offloading heavy computation, but so is for WASM etc.

Udash (or SJS in general) don't add too much in terms of web-worker support, it's not even designed for working in a multi-threaded client environment. I've seen some decent examples in frameworks more relevant to concurrency in the client (e.g. `akka.js-dom`), so to me the value of maintaining a separate subtemplate / adding features here as more of a burden than a feature. I'm actually considering moving some of the boilerplate away from this template, so the users can focus on the core features of the framework (building UI, using RPCs).

Should web-workers ever become a significant part of the framework, we'll certainly consider, but I can't justify it now.
