### ISSUE TITLE
chat demo

### ISSUE THREAD

**Issue by giuliohome** [UdashFramework/udash.g8#3]
after I build and run the demo

```
sbt compileStatics run
...
11:32:36.816 [run-main-1] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@267c1094{/,null,AVAILABLE}
11:32:36.856 [run-main-1] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@3d597c56{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
11:32:36.858 [run-main-1] INFO  org.eclipse.jetty.server.Server - Started @26891ms
11:32:36.862 [run-main-1] INFO  io.udash.logging.UdashLogger - Application started in 1s.
11:32:36.862 [run-main-1] INFO  io.udash.logging.UdashLogger - Click `Enter` to close application...
```
 

I open the browser (chrome or internet explorer on windows 7), I login as test/test or test2/test2 etc...

the error is `System: You don't have access to read the messages`
see screenshot [here](https://snag.gy/SMfpeN.jpg)

and the textbox to type messages is disabled ([image](https://snag.gy/rP7Xlz.jpg))

After many trials, sometimes it randomly works, but most of the time at least one of the two problems above is present,

BTW is there a more realistic tutorial, explaining how to protect the connection with _https_ and how to correctly manage the _security_ of the web app?

**Comment by giuliohome** [comment]
Oh... that was intentional!!!

The relevant code lines are [here](https://github.com/UdashFramework/udash.g8/blob/master/src/main/g8/backend/src/main/scala/$package$/backend/services/AuthService.scala#L29-L30)

Please, clarify such a thing when you present the demo! Thanks!

**Comment by Starzu** [comment]
@giuliohome You are right, this behaviour is at least surprising. We should extend the error messages and clarify that issue.

**Comment by giuliohome** [comment]
**Thank you! Much appreciated!**

Off Topic 1 
As a personal exercise, I've modified the code in a couple of points to show the name of the connected user (test/test2/test3) in the chat header (together with the number of total connections). No problem to share my code if anyone is interested, but of course these changes are very trivial and I'm just a beginner with Udash.

Off Topic 2
IMHO it would be interesting to show - at least in a readme - how to manage the security in a productive environment
1. what changes are required to use https instead of http
2. what changes are required (if any) to protect the backend services against tweaks (dev tools, etc.) from the client browser by malicious users, etc...

**Comment by Starzu** [comment]
The PR #4 adds information about random permissions on the login page. 

I think that Udash Guide is the best place to collect information about security management in production. I've put this on my TODO list. ;)
