### ISSUE TITLE
Packager sub-project example server.statics path not working

### ISSUE THREAD

**Issue by refond** [UdashFramework/udash.g8#6]
The packager sub-project example server.statics path does not work "as is" when using packaged 
`bin/the_start_script`. It requires being a directory level higher such as `../UdashStatics/WebContent` instead of `UdashStatics/WebContent` 

The following works for me:
```
# configuration for packager deployment

server {
  port = 9090
  statics = "../UdashStatics/WebContent"
}

auth.users = [
  "test:test",
  "test2:test2",
]
```

**Comment by ddworak** [comment]
Hi! Sorry for missing your question, I didn't have notifications set on this repo :disappointed: 

This depends on your working directory. If you run `bin/the_start_script` from the main directory which contains `bin lib UdashStatics` directories, all is well.

I'll add a mention of this being directory dependent to the text.
